#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SharedSample.Droid.Resource", IsApplication=true)]

namespace SharedSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Library.Android.Resource.Attribute.alpha = global::SharedSample.Droid.Resource.Attribute.alpha;
			global::Library.Android.Resource.Attribute.font = global::SharedSample.Droid.Resource.Attribute.font;
			global::Library.Android.Resource.Attribute.fontProviderAuthority = global::SharedSample.Droid.Resource.Attribute.fontProviderAuthority;
			global::Library.Android.Resource.Attribute.fontProviderCerts = global::SharedSample.Droid.Resource.Attribute.fontProviderCerts;
			global::Library.Android.Resource.Attribute.fontProviderFetchStrategy = global::SharedSample.Droid.Resource.Attribute.fontProviderFetchStrategy;
			global::Library.Android.Resource.Attribute.fontProviderFetchTimeout = global::SharedSample.Droid.Resource.Attribute.fontProviderFetchTimeout;
			global::Library.Android.Resource.Attribute.fontProviderPackage = global::SharedSample.Droid.Resource.Attribute.fontProviderPackage;
			global::Library.Android.Resource.Attribute.fontProviderQuery = global::SharedSample.Droid.Resource.Attribute.fontProviderQuery;
			global::Library.Android.Resource.Attribute.fontStyle = global::SharedSample.Droid.Resource.Attribute.fontStyle;
			global::Library.Android.Resource.Attribute.fontVariationSettings = global::SharedSample.Droid.Resource.Attribute.fontVariationSettings;
			global::Library.Android.Resource.Attribute.fontWeight = global::SharedSample.Droid.Resource.Attribute.fontWeight;
			global::Library.Android.Resource.Attribute.ttcIndex = global::SharedSample.Droid.Resource.Attribute.ttcIndex;
			global::Library.Android.Resource.Color.notification_action_color_filter = global::SharedSample.Droid.Resource.Color.notification_action_color_filter;
			global::Library.Android.Resource.Color.notification_icon_bg_color = global::SharedSample.Droid.Resource.Color.notification_icon_bg_color;
			global::Library.Android.Resource.Color.ripple_material_light = global::SharedSample.Droid.Resource.Color.ripple_material_light;
			global::Library.Android.Resource.Color.secondary_text_default_material_light = global::SharedSample.Droid.Resource.Color.secondary_text_default_material_light;
			global::Library.Android.Resource.Dimension.compat_button_inset_horizontal_material = global::SharedSample.Droid.Resource.Dimension.compat_button_inset_horizontal_material;
			global::Library.Android.Resource.Dimension.compat_button_inset_vertical_material = global::SharedSample.Droid.Resource.Dimension.compat_button_inset_vertical_material;
			global::Library.Android.Resource.Dimension.compat_button_padding_horizontal_material = global::SharedSample.Droid.Resource.Dimension.compat_button_padding_horizontal_material;
			global::Library.Android.Resource.Dimension.compat_button_padding_vertical_material = global::SharedSample.Droid.Resource.Dimension.compat_button_padding_vertical_material;
			global::Library.Android.Resource.Dimension.compat_control_corner_material = global::SharedSample.Droid.Resource.Dimension.compat_control_corner_material;
			global::Library.Android.Resource.Dimension.compat_notification_large_icon_max_height = global::SharedSample.Droid.Resource.Dimension.compat_notification_large_icon_max_height;
			global::Library.Android.Resource.Dimension.compat_notification_large_icon_max_width = global::SharedSample.Droid.Resource.Dimension.compat_notification_large_icon_max_width;
			global::Library.Android.Resource.Dimension.notification_action_icon_size = global::SharedSample.Droid.Resource.Dimension.notification_action_icon_size;
			global::Library.Android.Resource.Dimension.notification_action_text_size = global::SharedSample.Droid.Resource.Dimension.notification_action_text_size;
			global::Library.Android.Resource.Dimension.notification_big_circle_margin = global::SharedSample.Droid.Resource.Dimension.notification_big_circle_margin;
			global::Library.Android.Resource.Dimension.notification_content_margin_start = global::SharedSample.Droid.Resource.Dimension.notification_content_margin_start;
			global::Library.Android.Resource.Dimension.notification_large_icon_height = global::SharedSample.Droid.Resource.Dimension.notification_large_icon_height;
			global::Library.Android.Resource.Dimension.notification_large_icon_width = global::SharedSample.Droid.Resource.Dimension.notification_large_icon_width;
			global::Library.Android.Resource.Dimension.notification_main_column_padding_top = global::SharedSample.Droid.Resource.Dimension.notification_main_column_padding_top;
			global::Library.Android.Resource.Dimension.notification_media_narrow_margin = global::SharedSample.Droid.Resource.Dimension.notification_media_narrow_margin;
			global::Library.Android.Resource.Dimension.notification_right_icon_size = global::SharedSample.Droid.Resource.Dimension.notification_right_icon_size;
			global::Library.Android.Resource.Dimension.notification_right_side_padding_top = global::SharedSample.Droid.Resource.Dimension.notification_right_side_padding_top;
			global::Library.Android.Resource.Dimension.notification_small_icon_background_padding = global::SharedSample.Droid.Resource.Dimension.notification_small_icon_background_padding;
			global::Library.Android.Resource.Dimension.notification_small_icon_size_as_large = global::SharedSample.Droid.Resource.Dimension.notification_small_icon_size_as_large;
			global::Library.Android.Resource.Dimension.notification_subtext_size = global::SharedSample.Droid.Resource.Dimension.notification_subtext_size;
			global::Library.Android.Resource.Dimension.notification_top_pad = global::SharedSample.Droid.Resource.Dimension.notification_top_pad;
			global::Library.Android.Resource.Dimension.notification_top_pad_large_text = global::SharedSample.Droid.Resource.Dimension.notification_top_pad_large_text;
			global::Library.Android.Resource.Drawable.notification_action_background = global::SharedSample.Droid.Resource.Drawable.notification_action_background;
			global::Library.Android.Resource.Drawable.notification_bg = global::SharedSample.Droid.Resource.Drawable.notification_bg;
			global::Library.Android.Resource.Drawable.notification_bg_low = global::SharedSample.Droid.Resource.Drawable.notification_bg_low;
			global::Library.Android.Resource.Drawable.notification_bg_low_normal = global::SharedSample.Droid.Resource.Drawable.notification_bg_low_normal;
			global::Library.Android.Resource.Drawable.notification_bg_low_pressed = global::SharedSample.Droid.Resource.Drawable.notification_bg_low_pressed;
			global::Library.Android.Resource.Drawable.notification_bg_normal = global::SharedSample.Droid.Resource.Drawable.notification_bg_normal;
			global::Library.Android.Resource.Drawable.notification_bg_normal_pressed = global::SharedSample.Droid.Resource.Drawable.notification_bg_normal_pressed;
			global::Library.Android.Resource.Drawable.notification_icon_background = global::SharedSample.Droid.Resource.Drawable.notification_icon_background;
			global::Library.Android.Resource.Drawable.notification_template_icon_bg = global::SharedSample.Droid.Resource.Drawable.notification_template_icon_bg;
			global::Library.Android.Resource.Drawable.notification_template_icon_low_bg = global::SharedSample.Droid.Resource.Drawable.notification_template_icon_low_bg;
			global::Library.Android.Resource.Drawable.notification_tile_bg = global::SharedSample.Droid.Resource.Drawable.notification_tile_bg;
			global::Library.Android.Resource.Drawable.notify_panel_notification_icon_bg = global::SharedSample.Droid.Resource.Drawable.notify_panel_notification_icon_bg;
			global::Library.Android.Resource.Id.action_container = global::SharedSample.Droid.Resource.Id.action_container;
			global::Library.Android.Resource.Id.action_divider = global::SharedSample.Droid.Resource.Id.action_divider;
			global::Library.Android.Resource.Id.action_image = global::SharedSample.Droid.Resource.Id.action_image;
			global::Library.Android.Resource.Id.action_text = global::SharedSample.Droid.Resource.Id.action_text;
			global::Library.Android.Resource.Id.actions = global::SharedSample.Droid.Resource.Id.actions;
			global::Library.Android.Resource.Id.async = global::SharedSample.Droid.Resource.Id.async;
			global::Library.Android.Resource.Id.blocking = global::SharedSample.Droid.Resource.Id.blocking;
			global::Library.Android.Resource.Id.chronometer = global::SharedSample.Droid.Resource.Id.chronometer;
			global::Library.Android.Resource.Id.forever = global::SharedSample.Droid.Resource.Id.forever;
			global::Library.Android.Resource.Id.icon = global::SharedSample.Droid.Resource.Id.icon;
			global::Library.Android.Resource.Id.icon_group = global::SharedSample.Droid.Resource.Id.icon_group;
			global::Library.Android.Resource.Id.info = global::SharedSample.Droid.Resource.Id.info;
			global::Library.Android.Resource.Id.italic = global::SharedSample.Droid.Resource.Id.italic;
			global::Library.Android.Resource.Id.line1 = global::SharedSample.Droid.Resource.Id.line1;
			global::Library.Android.Resource.Id.line3 = global::SharedSample.Droid.Resource.Id.line3;
			global::Library.Android.Resource.Id.normal = global::SharedSample.Droid.Resource.Id.normal;
			global::Library.Android.Resource.Id.notification_background = global::SharedSample.Droid.Resource.Id.notification_background;
			global::Library.Android.Resource.Id.notification_main_column = global::SharedSample.Droid.Resource.Id.notification_main_column;
			global::Library.Android.Resource.Id.notification_main_column_container = global::SharedSample.Droid.Resource.Id.notification_main_column_container;
			global::Library.Android.Resource.Id.right_icon = global::SharedSample.Droid.Resource.Id.right_icon;
			global::Library.Android.Resource.Id.right_side = global::SharedSample.Droid.Resource.Id.right_side;
			global::Library.Android.Resource.Id.tag_transition_group = global::SharedSample.Droid.Resource.Id.tag_transition_group;
			global::Library.Android.Resource.Id.tag_unhandled_key_event_manager = global::SharedSample.Droid.Resource.Id.tag_unhandled_key_event_manager;
			global::Library.Android.Resource.Id.tag_unhandled_key_listeners = global::SharedSample.Droid.Resource.Id.tag_unhandled_key_listeners;
			global::Library.Android.Resource.Id.text = global::SharedSample.Droid.Resource.Id.text;
			global::Library.Android.Resource.Id.text2 = global::SharedSample.Droid.Resource.Id.text2;
			global::Library.Android.Resource.Id.time = global::SharedSample.Droid.Resource.Id.time;
			global::Library.Android.Resource.Id.title = global::SharedSample.Droid.Resource.Id.title;
			global::Library.Android.Resource.Integer.status_bar_notification_info_maxnum = global::SharedSample.Droid.Resource.Integer.status_bar_notification_info_maxnum;
			global::Library.Android.Resource.Layout.notification_action = global::SharedSample.Droid.Resource.Layout.notification_action;
			global::Library.Android.Resource.Layout.notification_action_tombstone = global::SharedSample.Droid.Resource.Layout.notification_action_tombstone;
			global::Library.Android.Resource.Layout.notification_template_custom_big = global::SharedSample.Droid.Resource.Layout.notification_template_custom_big;
			global::Library.Android.Resource.Layout.notification_template_icon_group = global::SharedSample.Droid.Resource.Layout.notification_template_icon_group;
			global::Library.Android.Resource.Layout.notification_template_part_chronometer = global::SharedSample.Droid.Resource.Layout.notification_template_part_chronometer;
			global::Library.Android.Resource.Layout.notification_template_part_time = global::SharedSample.Droid.Resource.Layout.notification_template_part_time;
			global::Library.Android.Resource.String.app_name = global::SharedSample.Droid.Resource.String.app_name;
			global::Library.Android.Resource.String.library_name = global::SharedSample.Droid.Resource.String.library_name;
			global::Library.Android.Resource.String.status_bar_notification_info_overflow = global::SharedSample.Droid.Resource.String.status_bar_notification_info_overflow;
			global::Library.Android.Resource.Style.TextAppearance_Compat_Notification = global::SharedSample.Droid.Resource.Style.TextAppearance_Compat_Notification;
			global::Library.Android.Resource.Style.TextAppearance_Compat_Notification_Info = global::SharedSample.Droid.Resource.Style.TextAppearance_Compat_Notification_Info;
			global::Library.Android.Resource.Style.TextAppearance_Compat_Notification_Line2 = global::SharedSample.Droid.Resource.Style.TextAppearance_Compat_Notification_Line2;
			global::Library.Android.Resource.Style.TextAppearance_Compat_Notification_Time = global::SharedSample.Droid.Resource.Style.TextAppearance_Compat_Notification_Time;
			global::Library.Android.Resource.Style.TextAppearance_Compat_Notification_Title = global::SharedSample.Droid.Resource.Style.TextAppearance_Compat_Notification_Title;
			global::Library.Android.Resource.Style.Widget_Compat_NotificationActionContainer = global::SharedSample.Droid.Resource.Style.Widget_Compat_NotificationActionContainer;
			global::Library.Android.Resource.Style.Widget_Compat_NotificationActionText = global::SharedSample.Droid.Resource.Style.Widget_Compat_NotificationActionText;
			global::Library.Android.Resource.Styleable.ColorStateListItem = global::SharedSample.Droid.Resource.Styleable.ColorStateListItem;
			global::Library.Android.Resource.Styleable.ColorStateListItem_alpha = global::SharedSample.Droid.Resource.Styleable.ColorStateListItem_alpha;
			global::Library.Android.Resource.Styleable.ColorStateListItem_android_alpha = global::SharedSample.Droid.Resource.Styleable.ColorStateListItem_android_alpha;
			global::Library.Android.Resource.Styleable.ColorStateListItem_android_color = global::SharedSample.Droid.Resource.Styleable.ColorStateListItem_android_color;
			global::Library.Android.Resource.Styleable.FontFamily = global::SharedSample.Droid.Resource.Styleable.FontFamily;
			global::Library.Android.Resource.Styleable.FontFamily_fontProviderAuthority = global::SharedSample.Droid.Resource.Styleable.FontFamily_fontProviderAuthority;
			global::Library.Android.Resource.Styleable.FontFamily_fontProviderCerts = global::SharedSample.Droid.Resource.Styleable.FontFamily_fontProviderCerts;
			global::Library.Android.Resource.Styleable.FontFamily_fontProviderFetchStrategy = global::SharedSample.Droid.Resource.Styleable.FontFamily_fontProviderFetchStrategy;
			global::Library.Android.Resource.Styleable.FontFamily_fontProviderFetchTimeout = global::SharedSample.Droid.Resource.Styleable.FontFamily_fontProviderFetchTimeout;
			global::Library.Android.Resource.Styleable.FontFamily_fontProviderPackage = global::SharedSample.Droid.Resource.Styleable.FontFamily_fontProviderPackage;
			global::Library.Android.Resource.Styleable.FontFamily_fontProviderQuery = global::SharedSample.Droid.Resource.Styleable.FontFamily_fontProviderQuery;
			global::Library.Android.Resource.Styleable.FontFamilyFont = global::SharedSample.Droid.Resource.Styleable.FontFamilyFont;
			global::Library.Android.Resource.Styleable.FontFamilyFont_android_font = global::SharedSample.Droid.Resource.Styleable.FontFamilyFont_android_font;
			global::Library.Android.Resource.Styleable.FontFamilyFont_android_fontStyle = global::SharedSample.Droid.Resource.Styleable.FontFamilyFont_android_fontStyle;
			global::Library.Android.Resource.Styleable.FontFamilyFont_android_fontVariationSettings = global::SharedSample.Droid.Resource.Styleable.FontFamilyFont_android_fontVariationSettings;
			global::Library.Android.Resource.Styleable.FontFamilyFont_android_fontWeight = global::SharedSample.Droid.Resource.Styleable.FontFamilyFont_android_fontWeight;
			global::Library.Android.Resource.Styleable.FontFamilyFont_android_ttcIndex = global::SharedSample.Droid.Resource.Styleable.FontFamilyFont_android_ttcIndex;
			global::Library.Android.Resource.Styleable.FontFamilyFont_font = global::SharedSample.Droid.Resource.Styleable.FontFamilyFont_font;
			global::Library.Android.Resource.Styleable.FontFamilyFont_fontStyle = global::SharedSample.Droid.Resource.Styleable.FontFamilyFont_fontStyle;
			global::Library.Android.Resource.Styleable.FontFamilyFont_fontVariationSettings = global::SharedSample.Droid.Resource.Styleable.FontFamilyFont_fontVariationSettings;
			global::Library.Android.Resource.Styleable.FontFamilyFont_fontWeight = global::SharedSample.Droid.Resource.Styleable.FontFamilyFont_fontWeight;
			global::Library.Android.Resource.Styleable.FontFamilyFont_ttcIndex = global::SharedSample.Droid.Resource.Styleable.FontFamilyFont_ttcIndex;
			global::Library.Android.Resource.Styleable.GradientColor = global::SharedSample.Droid.Resource.Styleable.GradientColor;
			global::Library.Android.Resource.Styleable.GradientColor_android_centerColor = global::SharedSample.Droid.Resource.Styleable.GradientColor_android_centerColor;
			global::Library.Android.Resource.Styleable.GradientColor_android_centerX = global::SharedSample.Droid.Resource.Styleable.GradientColor_android_centerX;
			global::Library.Android.Resource.Styleable.GradientColor_android_centerY = global::SharedSample.Droid.Resource.Styleable.GradientColor_android_centerY;
			global::Library.Android.Resource.Styleable.GradientColor_android_endColor = global::SharedSample.Droid.Resource.Styleable.GradientColor_android_endColor;
			global::Library.Android.Resource.Styleable.GradientColor_android_endX = global::SharedSample.Droid.Resource.Styleable.GradientColor_android_endX;
			global::Library.Android.Resource.Styleable.GradientColor_android_endY = global::SharedSample.Droid.Resource.Styleable.GradientColor_android_endY;
			global::Library.Android.Resource.Styleable.GradientColor_android_gradientRadius = global::SharedSample.Droid.Resource.Styleable.GradientColor_android_gradientRadius;
			global::Library.Android.Resource.Styleable.GradientColor_android_startColor = global::SharedSample.Droid.Resource.Styleable.GradientColor_android_startColor;
			global::Library.Android.Resource.Styleable.GradientColor_android_startX = global::SharedSample.Droid.Resource.Styleable.GradientColor_android_startX;
			global::Library.Android.Resource.Styleable.GradientColor_android_startY = global::SharedSample.Droid.Resource.Styleable.GradientColor_android_startY;
			global::Library.Android.Resource.Styleable.GradientColor_android_tileMode = global::SharedSample.Droid.Resource.Styleable.GradientColor_android_tileMode;
			global::Library.Android.Resource.Styleable.GradientColor_android_type = global::SharedSample.Droid.Resource.Styleable.GradientColor_android_type;
			global::Library.Android.Resource.Styleable.GradientColorItem = global::SharedSample.Droid.Resource.Styleable.GradientColorItem;
			global::Library.Android.Resource.Styleable.GradientColorItem_android_color = global::SharedSample.Droid.Resource.Styleable.GradientColorItem_android_color;
			global::Library.Android.Resource.Styleable.GradientColorItem_android_offset = global::SharedSample.Droid.Resource.Styleable.GradientColorItem_android_offset;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int alpha = 2130771968;
			
			// aapt resource value: 0x7f010008
			public const int font = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderAuthority = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderCerts = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchStrategy = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int fontProviderFetchTimeout = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderPackage = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderQuery = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int fontStyle = 2130771975;
			
			// aapt resource value: 0x7f01000a
			public const int fontVariationSettings = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int fontWeight = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int ttcIndex = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int notification_action_color_filter = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int notification_icon_bg_color = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int ripple_material_light = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int secondary_text_default_material_light = 2131165187;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060004
			public const int compat_button_inset_horizontal_material = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int compat_button_inset_vertical_material = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int compat_button_padding_horizontal_material = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int compat_button_padding_vertical_material = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int compat_control_corner_material = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int compat_notification_large_icon_max_height = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int compat_notification_large_icon_max_width = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int notification_action_icon_size = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int notification_action_text_size = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int notification_big_circle_margin = 2131099661;
			
			// aapt resource value: 0x7f060001
			public const int notification_content_margin_start = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int notification_large_icon_height = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int notification_large_icon_width = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int notification_main_column_padding_top = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int notification_media_narrow_margin = 2131099651;
			
			// aapt resource value: 0x7f060010
			public const int notification_right_icon_size = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int notification_right_side_padding_top = 2131099648;
			
			// aapt resource value: 0x7f060011
			public const int notification_small_icon_background_padding = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int notification_small_icon_size_as_large = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int notification_subtext_size = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int notification_top_pad = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int notification_top_pad_large_text = 2131099669;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000a
			public const int notification_template_icon_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notification_template_icon_low_bg = 2130837515;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090010
			public const int action_container = 2131296272;
			
			// aapt resource value: 0x7f09001c
			public const int action_divider = 2131296284;
			
			// aapt resource value: 0x7f090011
			public const int action_image = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int action_text = 2131296274;
			
			// aapt resource value: 0x7f09001d
			public const int actions = 2131296285;
			
			// aapt resource value: 0x7f090008
			public const int async = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int blocking = 2131296265;
			
			// aapt resource value: 0x7f09001b
			public const int chronometer = 2131296283;
			
			// aapt resource value: 0x7f09000a
			public const int forever = 2131296266;
			
			// aapt resource value: 0x7f090014
			public const int icon = 2131296276;
			
			// aapt resource value: 0x7f09001e
			public const int icon_group = 2131296286;
			
			// aapt resource value: 0x7f090017
			public const int info = 2131296279;
			
			// aapt resource value: 0x7f09000b
			public const int italic = 2131296267;
			
			// aapt resource value: 0x7f090000
			public const int line1 = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int line3 = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int normal = 2131296268;
			
			// aapt resource value: 0x7f090019
			public const int notification_background = 2131296281;
			
			// aapt resource value: 0x7f090015
			public const int notification_main_column = 2131296277;
			
			// aapt resource value: 0x7f090013
			public const int notification_main_column_container = 2131296275;
			
			// aapt resource value: 0x7f090018
			public const int right_icon = 2131296280;
			
			// aapt resource value: 0x7f090016
			public const int right_side = 2131296278;
			
			// aapt resource value: 0x7f09000e
			public const int sendEventButton = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int setIdentityButton = 2131296269;
			
			// aapt resource value: 0x7f09000f
			public const int startButton = 2131296271;
			
			// aapt resource value: 0x7f090002
			public const int tag_transition_group = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int tag_unhandled_key_event_manager = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int tag_unhandled_key_listeners = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int text = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int text2 = 2131296262;
			
			// aapt resource value: 0x7f09001a
			public const int time = 2131296282;
			
			// aapt resource value: 0x7f090007
			public const int title = 2131296263;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int status_bar_notification_info_maxnum = 2131361792;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int notification_action = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int notification_action_tombstone = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int notification_template_custom_big = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int notification_template_icon_group = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int notification_template_part_chronometer = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int notification_template_part_time = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int hello = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int library_name = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int status_bar_notification_info_overflow = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int TextAppearance_Compat_Notification = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int TextAppearance_Compat_Notification_Info = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int TextAppearance_Compat_Notification_Line2 = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int TextAppearance_Compat_Notification_Time = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int TextAppearance_Compat_Notification_Title = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int Widget_Compat_NotificationActionContainer = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int Widget_Compat_NotificationActionText = 2131230725;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ColorStateListItem = new int[] {
					16843173,
					16843551,
					2130771968};
			
			// aapt resource value: 2
			public const int ColorStateListItem_alpha = 2;
			
			// aapt resource value: 1
			public const int ColorStateListItem_android_alpha = 1;
			
			// aapt resource value: 0
			public const int ColorStateListItem_android_color = 0;
			
			public static int[] FontFamily = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					16844143,
					16844144,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 4
			public const int FontFamilyFont_android_fontVariationSettings = 4;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 3
			public const int FontFamilyFont_android_ttcIndex = 3;
			
			// aapt resource value: 6
			public const int FontFamilyFont_font = 6;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontStyle = 5;
			
			// aapt resource value: 8
			public const int FontFamilyFont_fontVariationSettings = 8;
			
			// aapt resource value: 7
			public const int FontFamilyFont_fontWeight = 7;
			
			// aapt resource value: 9
			public const int FontFamilyFont_ttcIndex = 9;
			
			public static int[] GradientColor = new int[] {
					16843165,
					16843166,
					16843169,
					16843170,
					16843171,
					16843172,
					16843265,
					16843275,
					16844048,
					16844049,
					16844050,
					16844051};
			
			// aapt resource value: 7
			public const int GradientColor_android_centerColor = 7;
			
			// aapt resource value: 3
			public const int GradientColor_android_centerX = 3;
			
			// aapt resource value: 4
			public const int GradientColor_android_centerY = 4;
			
			// aapt resource value: 1
			public const int GradientColor_android_endColor = 1;
			
			// aapt resource value: 10
			public const int GradientColor_android_endX = 10;
			
			// aapt resource value: 11
			public const int GradientColor_android_endY = 11;
			
			// aapt resource value: 5
			public const int GradientColor_android_gradientRadius = 5;
			
			// aapt resource value: 0
			public const int GradientColor_android_startColor = 0;
			
			// aapt resource value: 8
			public const int GradientColor_android_startX = 8;
			
			// aapt resource value: 9
			public const int GradientColor_android_startY = 9;
			
			// aapt resource value: 6
			public const int GradientColor_android_tileMode = 6;
			
			// aapt resource value: 2
			public const int GradientColor_android_type = 2;
			
			public static int[] GradientColorItem = new int[] {
					16843173,
					16844052};
			
			// aapt resource value: 0
			public const int GradientColorItem_android_color = 0;
			
			// aapt resource value: 1
			public const int GradientColorItem_android_offset = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
